// <auto-generated />
using System;
using BillGeneratorAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BillGeneratorAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260404055417_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BillGeneratorAPI.Models.Bill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GrandTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxPercent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("BillGeneratorAPI.Models.BillItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<int>("CatalogType")
                        .HasColumnType("int");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("BillId");

                    b.ToTable("BillItems");
                });

            modelBuilder.Entity("BillGeneratorAPI.Models.CatalogItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CatalogType")
                        .HasColumnType("int");

                    b.Property<bool>("IsVariablePrice")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("CatalogItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CatalogType = 1,
                            IsVariablePrice = false,
                            Name = "Adult Ticket",
                            Price = 200m
                        },
                        new
                        {
                            Id = 2,
                            CatalogType = 1,
                            IsVariablePrice = false,
                            Name = "Child Ticket",
                            Price = 100m
                        },
                        new
                        {
                            Id = 3,
                            CatalogType = 1,
                            IsVariablePrice = false,
                            Name = "Senior Ticket",
                            Price = 150m
                        },
                        new
                        {
                            Id = 4,
                            CatalogType = 1,
                            IsVariablePrice = false,
                            Name = "VIP Ticket",
                            Price = 500m
                        },
                        new
                        {
                            Id = 5,
                            CatalogType = 2,
                            IsVariablePrice = false,
                            Name = "Donation - 100",
                            Price = 100m
                        },
                        new
                        {
                            Id = 6,
                            CatalogType = 2,
                            IsVariablePrice = false,
                            Name = "Donation - 500",
                            Price = 500m
                        },
                        new
                        {
                            Id = 7,
                            CatalogType = 2,
                            IsVariablePrice = false,
                            Name = "Donation - 1000",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 8,
                            CatalogType = 2,
                            IsVariablePrice = true,
                            Name = "Custom Donation",
                            Price = 0m
                        },
                        new
                        {
                            Id = 9,
                            CatalogType = 3,
                            IsVariablePrice = true,
                            Name = "T-Shirt",
                            Price = 350m
                        },
                        new
                        {
                            Id = 10,
                            CatalogType = 3,
                            IsVariablePrice = true,
                            Name = "Cap",
                            Price = 200m
                        },
                        new
                        {
                            Id = 11,
                            CatalogType = 3,
                            IsVariablePrice = true,
                            Name = "Coffee",
                            Price = 80m
                        },
                        new
                        {
                            Id = 12,
                            CatalogType = 3,
                            IsVariablePrice = true,
                            Name = "Guide Service",
                            Price = 1000m
                        });
                });

            modelBuilder.Entity("BillGeneratorAPI.Models.BillItem", b =>
                {
                    b.HasOne("BillGeneratorAPI.Models.Bill", "Bill")
                        .WithMany("Items")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("BillGeneratorAPI.Models.Bill", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
